### ISSUE TITLE
module 'iocextract' has no attribute 'refang_url'

### ISSUE THREAD

**Issue by Bronya-Rayi** [InQuest/iocextract#70]
There is a problem with the latest version of the source code on pypi

![image](https://user-images.githubusercontent.com/47048823/233846472-8c70b2ef-2907-4cd4-bc31-a8ddfe67b314.png)

**Comment by Bronya-Rayi** [comment]
The threatingestor is still using the refang_url function

**Comment by azazelm3dj3d** [comment]
Posting the response from the ThreatIngestor issue to help keep track of both.

Comment: https://github.com/InQuest/ThreatIngestor/issues/143#issuecomment-1519087357
